### PR TITLE
enhance ja_jp.lang

### PR DESCRIPTION
**Pull request by karakufire**
I cannot locate these entries in game:
+ updating consider
+ Line 494 - gui.structure
+ Line 569 - gui.securityOffline
+ Line 580 - gui.stockControl
+ Line 581 - gui.allowDefault
+ Line 582 - gui.sizeMode
+ Line 606 - gui.factory.secondaryEnergy
+ Line 783 - tooltip.conduction
+ Line 784 - tooltip.insulation
+ Line 785 - tooltip.heatCapacity
+ Line 908 - sideData.Fill
+ Line 909 - sudeData.Empty
+ Line 910 - sideData.Charge
+ Line 911 - sideData.Discharge

Could developers teach me where are these entries used in?
For improving my translation, I need to know how are used these entries.

### CODE REVIEW

**Comment by thiakil** [comment]
- `gui.structure` - can't find any usages in code
- `gui.securityOffline` - error message used when the security frequency data is not present
- `gui.stockControl` - Formulaic Assemblicator GUI
- `gui.allowDefault` - Tooltip in item filters (such as the Digital Miner), I believe for allowing default transporter route
- `gui.sizeMode` - Itemstack filters, enables filtering on stack size
- `gui.factory.secondaryEnergy` - doesn't appear used
- `tooltip.conduction`, `tooltip.insulation`, `tooltip.heatCapacity` - Thermodynamic conductor tooltip
- `sideData.Fill`, `sideData.Empty`, `sideData.Charge`, `sideData.Discharge` - doesn't appear used

**Comment by karakufire** [comment]
Thank you, @thiakil . Thanks to you, I can make better translation.

**Comment by karakufire** [comment]
And, I cannot locate announce of upgrade consider. Is the way to appear it arbitrarily?

**Comment by thiakil** [comment]
I do not understand what you are asking?

**Comment by karakufire** [comment]
Sorry my poor English.
Does command to appear announce of update exist? It's I want to say.

**Comment by thiakil** [comment]
I don't believe so, you'd need to download an older version of a mod

**Comment by karakufire** [comment]
I see...

**Comment by karakufire** [comment]
OK.
Should I translate this comment-out-ed entries?
 * Line 891: tooltip.ReactorNeutronCapturePlate

**Comment by karakufire** [comment]
OK.

**Comment by thiakil** [comment]
It does not matter if they are understood as-is, if they are the *exact same* as the en_us file, they should be removed.

**Comment by karakufire** [comment]
I have a question. 
Does you said "remove" not mean "have to translate"?

**Comment by thiakil** [comment]
No, if they are understood the same as the English version, it does not need to be in the file.

If a key is not present, the game will pull it from the en_us file instead. This way, if it changes in the future the other languages will get the new name (until its translation is reviewed)

**Comment by karakufire** [comment]
Thank you, I understood. I'm going to delete keys whats same as en_us.lang's from ja_jp.lang.

**Comment by dizzyd** [comment]
Hi @karakufire - I've merged this into my fork and it will be part of the 9.4.17 release (https://minecraft.curseforge.com/projects/mekanism-tools-dz-edition) later today. Thanks!

**Pull request merged**
