### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by Mastergalen**
Allows the project to use Jenkin's [declarative pipeline syntax](https://jenkins.io/doc/book/pipeline/syntax/).

### CODE REVIEW

**Comment by thiakil** [comment]
First of all, why? AFAIK auto builds are already setup behind the scenes...

Second of all, where is there an api key in the file?!

**Comment by thommy101** [comment]
I know a bit of S3 storage, and that isn't an api key ;)
It's a Jenkins user which contains the 2 secrets needed.
https://github.com/jenkinsci/pipeline-aws-plugin#withaws

This is either something @aidancbrady requested, or something that's unwanted.

Also, this should target development, not master

**Comment by aidancbrady** [comment]
We're moving site-specific deployment to AWS S3 instead of the raw webserver. Definitely intentional!

**Comment by thiakil** [comment]
@Mastergalen the jenkins server seems to be using a still old version of gradle, despite 4.4 being specified in the jenkinsfile

It could also potentially use the gradle wrapper script (`./gradlew`)

**Pull request merged**
