### PR TITLE
Update to 1.10

### PR DESCRIPTION
**Pull request by miuirussia**
Updated to Minecraft 1.10

### CODE REVIEW

**Comment by mimikal** [comment]
Mekanism is for 1.9. Also, there is no Forge for 1.10 yet. So basically you
have to use 1.9.

**Comment by miuirussia** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.html

**Comment by mimikal** [comment]
Oh, it probably only came out a week ago or something then. Either way,
Mekanism 9 only works on Forge 1.9.

**Comment by aidancbrady** [comment]
I've ported your changes to the 1.10 branch. Appreciate it :)

**Pull request closed without merging**
