### PR TITLE
[1.11] Fix handling of consumable item fluid containers.

### LINKED ISSUE #4539: [1.11.2] Placing water in a machine with a forestry tin can or capsule causes a ticking tile entity
Using a forestry tin can or capsule instead of a bucket in Mekanism machines causes ticking block crash.

1. Place electrolytic separator
2. Put water can in water slot
3. Crash

Mekanism 307
Forge 13.20.1.2386
Minecraft 1.11.2

Log:
https://paste.ee/p/oxUq9

### PR DESCRIPTION
**Pull request by thommy101**
Fixes #4539.
Also added some null checks and fixed some compiler warnings

### CODE REVIEW

**Comment by thiakil** [comment]
@aidancbrady this currently breaks normal buckets!

**Comment by thommy101** [comment]
Huh, I've tested it with buckets? :s weird

**Comment by thommy101** [comment]
I know what went wrong with my testing. The Forge buckets where enabled. Only tested those not the default Vanilla buckets

**Comment by thiakil** [comment]
ahhhh, that'd do it. I'm guessing you have tinkers installed?

**Comment by thommy101** [comment]
Pfff, test World right from idea. \*looks at folder\*
Yep!

**Pull request merged**
