### PR TITLE
Development

### PR DESCRIPTION
**Pull request by TehStoneMan**
Changed name of "Obsidian Ingot" to "Refined Obsidian Ingot" to avoid confusion with obsidian ingots for other mods (for example Tinker's Construct)

### CODE REVIEW

**Comment by aidancbrady** [comment]
Thanks!

**Comment by KamranMackey** [comment]
@TehStoneMan: uh, please don't use "Development" as the PR title...use an actual title that's detailed, as it's confusing when you just use "Development" as the title.

**Comment by TehStoneMan** [comment]
Sorry. Guess I forgot to change that from default.

**Comment by aidancbrady** [comment]
@KamranMackey, it's really no issue. He provided a nice detailed explanation inside of the changes he made and why he did so.

**Pull request merged**
