### PR TITLE
Remove BuildCraft fuel integration

### PR DESCRIPTION
**Pull request by tgstyle**
Fix SpongeForge 7.0.0-BETA-2568 Compatibility

### CODE REVIEW

**Comment by tgstyle** [comment]
Appears to be something with this SpongeForge commit
https://github.com/SpongePowered/SpongeForge/commit/5de88e706c84c549cd2415795910d3be7be8c0bd
BC is not on 1.12.1 anyway, integration could be re-added later

**Comment by thommy101** [comment]
I'll reopen this if you've provided the requested information (preferably a complete bug report with logs)

**Comment by tgstyle** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1732 contains the crashlog

**Comment by thommy101** [comment]
Sorry, but this is something SpongeForge should fix, that code is guarded by `Loader.isModLoaded()` and should never run when buildcraft isn't present. It works perfectly with forge. 

SpongeForge is probably loading stuff it shouldn't do. 

If any of the Sponge developers need help debugging, I'm certainly willing to help finding a solution.

**Comment by thommy101** [comment]
@tgstyle Could you confirm the latest spongeforge version fixes your issue?

**Comment by tgstyle** [comment]
Sponge 2577 still has the issue with Mekanism

**Pull request closed without merging**
