### PR TITLE
Water to heavy water

### PR DESCRIPTION
**Pull request by chaos234**
Added a secound way to aquire Deuterium because the current functionallity of the pump produces server lags and also it eats up all the water so that it will dissapear and must be replaced with new water.

The process is desinged like in issue #2988 but not over a new SEP (thought as GSP) to work like the Girdler-Sulfid-Process. It is desinged to work with the C. Infuser, C. Washer and Electrolytic Seperator to get enriched and finally to get Deuterium.

For detailed informations look at the image below and feel free to ask me, if there are some questions left.

Image:
newdeuteriumprocessing

Edit 1:

If there a false tab widht let me know this so that I can correct it in my IntelliJ IDEA.

### CODE REVIEW

**Comment by chaos234** [comment]
I see that my last commit included my opaque code requested from #3089 . Hope that this doesn't matter but it should work fine (multiplayer test pending).

**Comment by aidancbrady** [comment]
This is a fantastic, well-fleshed-out addition. Might I suggest actually making this a Mekanism add-on instead of adding it to the mod itself?  If you do, I'd be happy to reference it on Mekanism's website.

**Comment by chaos234** [comment]
Thanks for your positive replay @aidancbrady .

Ok, that's not the problem making it as a seperate AddIn/AddOn for Meka if you can give me blank package where I can include my work.

At this point I'll ask you what you are thinking about the last - let me say 10-15 comments - in the ticket because I don't know if you like a 24/7 production with only onetime input (e. g. a furnace is burning 24/7 if it get at last one burning material). I don't like such things and it will be glad to read your meaning about that what is written there.

At the secound point there is the opaque feature also inside if you look at the last commits. If you can pick up them - I can pack the changed images for you and send them as mail attachment - and include this in the next update it will be nice because it disables the client side rendering but I missed the step to make a separate branche for this incl. a separate pull request, how ever, it works ;).

Oh, last thing before I am going to sleep ... you should already have a mail from me, can you check you p. b. for that mail?

Have a nice day/evening/night what ever time is it (on my side 1:09 am - Germany ^^)

**Comment by aidancbrady** [comment]
@chaos234, the mod would be your own- you could use whatever package naming you wanted. If you wished to tie it in as specifically a Mekanism module, you could just use the "mekanism.<module>.*" naming that I use for MekanismGenerators and MekanismTools and have your main class implement IModule, use my source code if you want some insight.  

Whichever method you choose, as the mod would be under your own name, I'd also have no problems with you using an advertisement service and making revenue off downloads :)

**Comment by aidancbrady** [comment]
Also, by mail do you mean email?  I just checked and I didn't see anything from you.

**Comment by chaos234** [comment]
No email from me? Then it was deleted as my system crashed at this day, how bad :/.

But it doesn't matter as we can write here or we can meet us in your IRC, let me know
when you can be there so that we can talk about how to made my changes as addon
possible ;).


Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
Am 16.02.2016 05:00:46 schrieb Aidan <notifications@github.com>:
Also, by mail do you mean email? I just checked and I didn't see anything from you.

**Comment by chaos234** [comment]
Well, did you have a documentation how I can/should make my changes as an AddIn/AddOn?
Because in the next few weeks I have many small tests and many class tests so I don't have many time for this.

**Comment by aidancbrady** [comment]
I don't have any documentation available for this kind of thing right now.

What I would recommend is looking at the structure of my code for MekanismGenerators and MekanismTools- you're basically creating a mod that is completely dependent upon the Mekanism core module's code (note that you should not reference any code form the tools or generators module).  

Firstly, make sure you add this to your main class's @Mod declaration: dependencies = "required-after:Mekanism"

Note how the MekanismGenerators and MekanismTools main classes implement the IModule interface.  In the init() method, there's also the line "Mekanism.modulesLoaded.add(this);" which adds the mod to Mekanism's list of modules.  Follow these guidelines if you want your mod to be truly registered as a module.

That's honestly all you need to worry about.  You can create your own package structure and code in whatever way you like as long as you follow the module registration and Mekanism dependency.  I'm here to help with any other questions you may have too :)

**Comment by chaos234** [comment]
Ok, I'll take a look until next week. How should I push it to you? Over a new and clean branche?

What is with my cahnges according to the opaque value? Should I make therefor a new pull request in a new branch with the latest source? Because both changes are different.

**Pull request closed without merging**
