### PR TITLE
InstanceOf check to avoid issues with railcraft.

### PR DESCRIPTION
**Pull request by clienthax**

### CODE REVIEW

**Comment by clienthax** [comment]
```
java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to net.minecraftforge.fluids.IFluidHandler
	at mekanism.common.FluidNetwork.getAcceptors(FluidNetwork.java:305)
	at mekanism.common.FluidNetwork.tickEmit(FluidNetwork.java:139)
	at mekanism.common.FluidNetwork.onUpdate(FluidNetwork.java:248)
	at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:343)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:105)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:91)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1022_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

```
I have had other issues with the HiddenBlock before, I believe it's what RC uses for steam/heat, however MC has never really been good at passing in the correct tile entity..

**Comment by clienthax** [comment]
https://github.com/Railcraft/Railcraft/issues/811

**Comment by clienthax** [comment]
https://github.com/aidancbrady/Mekanism/issues/3200 , apparently this was fixed before (with no commit reference yay)

**Comment by thiakil** [comment]
What. How would the game get mixed up with tile entities?! That sounds like someone else doing something screwy.

**Comment by clienthax** [comment]
You have obviously never written render code for mc :)
Stack trace is there and issue is from 2 years ago originally, every mod seems to just do instance of checks too.

**Comment by thiakil** [comment]
Quit with the attitude. If minecraft does not return the correct tile entity on a getTilentity *something else is broken* data structures don't just randomly decide to give a different value.

**Comment by thiakil** [comment]
At the absolute least you need to make this PR revalidate the acceptors in the next world tick.

**Pull request closed without merging**
