### PR TITLE
Changes to GUI's

### PR DESCRIPTION
**Pull request by TehStoneMan**
I have been making some changes to a number of GUI elements to provide more flexibility and visual consistency between machines. Been working through the order of machines as listed in BlockMachine.java, so only a handful have been touched so far.

Key changes consist of:
Replacing some hard-coded values with variables in GuiElement.java and derivatives to allow for more flexible placement.
Placing power bar and power input slot in similar positions on each GUI - In some cases this requires rearranging other GUI elements.
This also reflects in the idea of "Inputs on the left, outputs on the right"
"Iconify" progress bars - have the progress bars visually reflect the machine's function. This is a part of some forward planning in that similar looking progress bars can be used in the factories to show the function of that factory.

### CODE REVIEW

**Comment by aidancbrady** [comment]
Excellent work, thanks

**Comment by aidancbrady** [comment]
@TehStoneMan, your changes have messed up the progress bars in NEI components a bit.  Would you mind fixing them up to match what you've added?

**Comment by aidancbrady** [comment]
Reversing commits for now

**Comment by TehStoneMan** [comment]
Taken me a while to work out the NEI stuff, but now that I have a handle on it, shouldn't be too hard to fix it up

**Pull request merged**
