### PR TITLE
This is never this simple, what am I missing?

### PR DESCRIPTION
**Pull request by drunkripper**
I'm hoping this fixes it, but when are these things actually this easy?

### CODE REVIEW

**Comment by thiakil** [comment]
That is indeed all I changed in the 1.12 branch. Make sure you actually test it though.

**Comment by drunkripper** [comment]
How do I build it though with Gradle?

**Comment by tenten8401** [comment]
99% of the time it's just a `./gradlew build` as I recall.
drunkripper:patch-1 built successfully, I'll see if I can test it out.

**Comment by tenten8401** [comment]
I just tested this on a server affected with the issue and it does not seem to fix the issue.
image
The CPU spikes can still be associated with the IC2 EnergyNet removal:
image

**Comment by thiakil** [comment]
I don't see how the CPU usage is relevant... that's not something we can control.

**Comment by tenten8401** [comment]
It's causing chunks to be loaded that shouldn't be loaded and therefore
increasing the CPU utilization to levels that really interfere with
gameplay.

**Comment by thiakil** [comment]
Then you should be reporting that to IC2. Registration with ENET is just an event firing.

**Comment by tenten8401** [comment]
However I do not believe it's being registered properly with IC2 in the
first place though.

**Comment by thiakil** [comment]
the boolean is only set after the event has been sent :man_shrugging:

**Pull request merged**
