### PR TITLE
Fixed gas fluid not being gaseous.

### PR DESCRIPTION
**Pull request by halvors**
Hi!

I ran into some compatibility issues with some other mods that expects gas fluids to be gaseous.
I suspect that this is a detail that was overlooked when migrating to the new forge fluid system.

Fluids that have the same name is usually not added twice, but instead mods use the first one registered, when other mods expect gases to be set to gaseous issues might occur.

Please backport this as well if possible to 1.10 and 1.11 as many modders is still one these versions.
I wasn't sure how to submit this PR to all the branches at once, but as this is a 1 line fix it should be fairly easy to backport. Code works for all 1.10+ versions of minecraft. 

Thanks.

### CODE REVIEW

**Comment by thiakil** [comment]
Those fluids are not gasses as far as I can see. They are the Rotary Condensentratored liquids.

See `mekanism.common.MekanismFluids#register`

**Comment by halvors** [comment]
@thiakil Isn't steam a gas? Strange that the class is called Gas otherwise.

**Comment by thiakil** [comment]
Steam does not use the `Gas` class in Mekanism, and is already set to `Gaseous`

**Comment by halvors** [comment]
Hmm. Ok i understand. My bad. Just confusing that mekanism is using the gas system for liquids?...

**Comment by thiakil** [comment]
Not sure what you mean? Mekanism gasses can be converted to a liquid form using a Rotary Condensentrator. These liquids are standard MC Fluids.

**Pull request closed without merging**
