### PR TITLE
Fix more UUID changes. Fix Robit owner.

### PR DESCRIPTION
**Pull request by thommy101**
Fixes: #4342 and #4345.

### CODE REVIEW

**Comment by thommy101** [comment]
Changed all nbt references from owner to ownerUUID (to prevent crashes) and updated the Robit to have an owner UUID instead of an owner username.

**Comment by aidancbrady** [comment]
The one issue I see with this is that UsernameCache is not synchronized on the client, hence clientUUIDMap in MekanismClient.  I'm gonna do some extra testing to make sure everything works properly.

**Comment by thommy101** [comment]
Oh, didn't know that. Haven't tested the Robit to be honest. All other things are working fine.

**Comment by aidancbrady** [comment]
Yeah, everything else looks great. I'll do some changes to make sure the Robit works properly on the client.

**Pull request merged**
