### PR TITLE
Changes to Logistical Sorter GUI

### PR DESCRIPTION
**Pull request by TehStoneMan**
I have made a couple of changes to the GUI to make the scrollbar work with the mouse wheel, as well as a couple of graphic improvements.
I have also added buttons to allow changing the order of filters. Currently these buttons don't do anything, but I am working on that part.

### CODE REVIEW

**Comment by aidancbrady** [comment]
This is actually very cool.  Would it be possible for you to add these features for the Digital Miner as well (for consistency)?

**Comment by TehStoneMan** [comment]
It should be possible. I didn't think of the digital miner because I have not yet used one, but I will look into it.

**Comment by TehStoneMan** [comment]
Have now added the changes to the Digital Miner

**Comment by aidancbrady** [comment]
Great! Should I wait for you to finish implementing the up/down arrows?

**Comment by TehStoneMan** [comment]
It's all done and working already.

**Comment by aidancbrady** [comment]
Fantastic!

**Pull request merged**
