### PR TITLE
Remove hard dep on unnecessarily new forge version

### PR DESCRIPTION
**Pull request by tterrag1098**
There is no need to depend on such a new version, it only frustrates users who cannot update. I have tested a custom build with this code on the very latest forge release, and everything fluid related works perfectly fine.

It will now build on Forge 1291 (the *recommended* version for users)

### CODE REVIEW

**Comment by Barhandar** [comment]
>on the very latest forge release, and everything fluid related works perfectly fine.

So Forge got annoyed enough to reimplement compatibility for old fluid handling, or what? Railcraft's "we can do both Forges, come at me bro" should be [around there](https://github.com/CovertJaguar/Railcraft/tree/master/src/main/java/mods/railcraft/common/fluids).

**Comment by tterrag1098** [comment]
Yes, exactly. There are not many things you *need* one version or the other
for.

**Comment by tterrag1098** [comment]
Any news on this? Many users can't use Mek ATM because of this...

**Comment by aidancbrady** [comment]
Sorry, my schedule has been crazy recently. Mark my words- there will be a release this weekend :)

**Comment by aidancbrady** [comment]
@tterrag1098, I can't compile Mekanism under the very latest Forge versions- fluidID still doesn't exist. Is there something I'm missing?

**Comment by tterrag1098** [comment]
It doesn't need to...just compile using 1291 as the gradle.properties
specifies.

**Comment by aidancbrady** [comment]
@tterrag1098, thanks.

**Pull request merged**
