### PR TITLE
Fix for Paper-Recipecompability

### PR DESCRIPTION
**Pull request by GityUpNow**
I fixed one small Issues:

#4901
I replaced Mekanism-Sawdust in the Paper-Recipe with generic Sawdust from the OreDictionary, which should fix the problem

### CODE REVIEW

**Comment by GityUpNow** [comment]
Sorry, forgot to regenerate ^^'
Yeah, I tested it, everything seems to work to as planned. The Paper-Recipe is now also accepting Thermalexpansion-Sawdust.

Concerning the second part:
It seems so, there are no typos, both used names are the most commonly used for Sawdust and the call to the OreDictionary seems to be correct as well.

**Comment by thommy101** [comment]
Thanks! Will review soon... I think there might be a slight issue with my recipe generation code. The recipe type is not defined correctly.
Don't worry, it's something I will look at ;)

**Comment by GityUpNow** [comment]
Glad to help ^^

**Comment by thommy101** [comment]
Aah.. Already see what's wrong.. Could you please apply these changes on the 1.12 branch and open a PR to that branch? That contains a fix from me (since last week) to properly define recipe types :)

**Comment by GityUpNow** [comment]
Okay, learned a ton of stuff about git.

Closing this PR now.

**Pull request closed without merging**
