### PR TITLE
1.12

### PR DESCRIPTION
**Pull request by EliogabalusPL**
New file translating into Polish module Mekanism. Works in version 1.12 / 1.12.1 (Mekanism 9.4 - 9.4.1.326)
Unfortunately the old file pl_pl.lang was incompatible with modules 1.12 and 1.12.1 (down I did not check)
[https://1drv.ms/u/s!At_Q76MtyFIHhw3cT7QHG8jlVObl](url)

### CODE REVIEW

**Comment by thommy101** [comment]
Looks like something went wrong ;)

**Comment by thommy101** [comment]
I'll merge the translation tomorrow. Just saw the link in your message.

**Comment by EliogabalusPL** [comment]
I found an error in the file pl_pl.lang. Unfortunately I'm not able to post this error in GitHub (I do not know how to do it).

On line 1103 there is an error in the variable name
is: item.LazuliPaxel.name =
should be: item.LapisLazuliPaxel.name =
I do not write names by the "=" because there are in the words specific diacritic fonts for the Polish language and correcting them without having set Windows into Polish can change them to unreadable for Polish language fonts.

Can you help me to report this error?
Thank you in advance

Regards
Eliogabalus (aka PC_Maniac)

Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: poniedziałek, 9 października 2017 22:16
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12 (#4757)


I'll merge the translation tomorrow. Just saw the link in your message.

**Comment by thommy101** [comment]
I was just going over your translation and adding it to the 1.12 branch ;) Will take that with it

**Comment by thommy101** [comment]
It seems you've missed a couple translations (they are in the language files which aren't released yet). If you want me to add them, please provide the translation and I'll add them ;)

```
//Nuggets
item.obsidianNugget.name=Refined Obsidian Nugget
item.osmiumNugget.name=Osmium Nugget
item.bronzeNugget.name=Bronze Nugget
item.glowstoneNugget.name=Glowstone Nugget
item.steelNugget.name=Steel Nugget
item.copperNugget.name=Copper Nugget
item.tinNugget.name=Tin Nugget


```

**Comment by thommy101** [comment]
The current changes are now in the 1.12 branch (5f43d1e029be880362b4c1e9f90aa135a64fe48e) and will be released in the next public release.

**Comment by EliogabalusPL** [comment]
It would be funny to have brown nuggets and steel, because it is metal alloys. But it's just a game (though it's a little fantasy).

Polish translate

//Nuggets
item.obsidianNugget.name=Rafinowany samorodek obsydianu
item.osmiumNugget.name=Samorodek osmu
item.bronzeNugget.name=Samorodek brązu
item.glowstoneNugget.name=Samorodek jasnogłazu
item.steelNugget.name=Samorodek stali
item.copperNugget.name=Samorodek miedzi
item.tinNugget.name=Samorodek cyny


I do not know what is the situation with copying and pasting from Polish e-mail fonts, so just in case, I also send this translation in the form pl_pl.lang where the Nugets section is added at the end of the file.

Are there any differences between the en_us.lang file that I have and the one that you're getting ready for release?

Regards
Eliogabalus (aka PC_Maniac)


Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: wtorek, 10 października 2017 19:05
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12 (#4757)


It seems you've missed a couple translations (they are in the language files which aren't released yet). If you want me to add them, please provide the translation and I'll add them ;)

//Nuggets

item.obsidianNugget.name=Refined Obsidian Nugget

item.osmiumNugget.name=Osmium Nugget

item.bronzeNugget.name=Bronze Nugget

item.glowstoneNugget.name=Glowstone Nugget

item.steelNugget.name=Steel Nugget

item.copperNugget.name=Copper Nugget

item.tinNugget.name=Tin Nugget

**Comment by thommy101** [comment]
These translations where added yesterday. I'll add yours.

Github doesn't show attachments when you reply by mail ;)

**Comment by EliogabalusPL** [comment]
I do not know how to use Gitub with the file string.
I understand that in the text file included on the red background are old lines.
Green is the change that happens?
But then the entire Lapis Lazuli section has no new, correct lines. Not only are there old variable names that you no longer use, but also partial translations in this section.

This error, which I wrote to you in an earlier email, came from the fact that I did not notice in the old file pl_pl.lang that a lot of variables have changed. One line unfortunately missed. But in the file you posted on GitHub such red lines with bad variables is more (section // Lapis Lazuli is this glorious example)

Regards
Eliogabalus (aka PC_Maniac)

Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: wtorek, 10 października 2017 19:22
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12 (#4757)


The current changes are now in the 1.12 branch (5f43d1e<https://github.com/aidancbrady/Mekanism/commit/5f43d1e029be880362b4c1e9f90aa135a64fe48e>) and will be released in the next public release.

**Comment by thommy101** [comment]
I can assure you, all the lines are there ;) it just looks a bit weird, the Lapis Lazuli lines have been moved a bit down ;)

The whole file (not only the change) is available at: https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/resources/assets/mekanism/lang/pl_pl.lang

**Comment by EliogabalusPL** [comment]
I added to the file pl_pl.lang on Github 3 patches, since it turned out that the variables used in this file are from the old version of Mekanism and version 1.12 did not work.
Unfortunately, despite the fact that a few days have passed, the Github version still functions with erroneous variables. '
For example:
Line 838 -
"tooltip.ElectricChest =" is an old variable because you are currently using a variable:
"Tooltip.PersonalChest ="
Unfortunately I can not remember the other 2 bugfixes I found, but I posted those patches somewhere on Gitub. As I see, they have not entered the updated version of pl_pl.lang so the variables do not work and the names of these 3 elements will be displayed in English.

I still have some suggestions for fixing Polish names for cables and pipes, but until I know how to add them to Github (please explain how it's done to make my work not go bad), I refrain from adding them.

**Pull request closed without merging**
