### PR TITLE
Update to the latest vesion of the ComputerCraft API (19e4c03)

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by thiakil** [comment]
As mentioned in the other PR, I'd really prefer this was added as a gradle dep, or as a compiled jar in a libs folder at minimum (we've moved everything else we can to gradle). Likely requires work on CC's end or a custom build.

**Comment by josephcsible** [comment]
> Likely requires work on CC's end or a custom build.

Yeah, they don't offer a repository or even a jar right now. I opened dan200/ComputerCraft#446 about it. Can we do this for now, then switch to a gradle dep or a jar once they get one added?

**Comment by thiakil** [comment]
Does the integration work without this PR?

**Comment by aidancbrady** [comment]
Any updates on this?

**Comment by thiakil** [comment]
doesn't look like we got any progress on CC's side. I can generate an API jar for us this weekend though if we wanna go that way

**Comment by aidancbrady** [comment]
@thiakil, that sounds like a good option for now. Let me know once it's ready and one of us can add it in as a maven dep.

**Comment by thiakil** [comment]
added on my maven server and our 1.12 branch, changes available on https://github.com/thiakil/ComputerCraft/tree/api-jar if wanted to host elsewhere

**Pull request closed without merging**
