### PR TITLE
[1.10] Fix build on Windows; Fix machines randomly rotating and losing state; Tiny optimization

### PR DESCRIPTION
**Pull request by Ricket**
I thought this makes sense as 3 separate pull requests but can't figure out how to do that.

See commit messages...

### CODE REVIEW

**Comment by mezz** [comment]
To create three pull requests you need three branches.

Create a new one like this: (assume `origin` is Mekanism github and `ricket` is yours)
```
git checkout -b <featureName1> origin/1.10
git cherry-pick <sha of commit you want>
git push ricket
```

Repeat for each of the three commits.

**Comment by Ricket** [comment]
Whaat.. Those other commits I simply pushed to my fork, they definitely aren't supposed to be part of this pull request. I don't know how this works.

I see the message now, "Add more commits by pushing to the 1.10 branch on Ricket/Mekanism." That's definitely not what I intended.

**Comment by TehStoneMan** [comment]
The way GitHub works is that if you create a PR from a branch, any future commits to that branch get added to the PR until it is merged or closed. That's why it's best to have separate branches for each PR you wish to make.

**Comment by thommy101** [comment]
Any chance you can retry the original pull request? Think it would be quite nice to have it as there are still a lot of sync/desync issues.

If you don't have time I can try and cherry pick them into a new pull request.

**Pull request closed without merging**
